### ISSUE TITLE
[EPIC] simplify Amino/Protobuf hurdles, making it easy to craft transactions as a client-side developer.

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/telescope#11]
# Sprint 1
- [x] #13
- [x] #18
- [x] #19
- [x] #17 
- [x] #21 

- [x] name collisions that derive from the proto files

In regards to the prototype https://github.com/pyramation/osmosis-protobufs when running files as the input, getting this error, so I instead created a for loop and am generating the types for each proto file individually. filed issue here https://github.com/osmosis-labs/osmosis/issues/1185

```
osmosis/gamm/v1beta1/tx.proto:9:9: "osmosis.gamm.v1beta1.Msg" is already defined in file "osmosis/gamm/pool-models/balancer/tx.proto"
```

- [x] missing protobuf references

some protobuf references version don’t exist (e.g. https://github.com/gogo/protobuf/issues/737 ) so I found them here https://github.com/regen-network/protobuf

- [x] use babel to transpile the result and make better TS objects

https://github.com/cosmology-finance/cosmology/blob/master/packages/protobufs/src/proto/osmosis/gamm/v1beta1/tx.ts#L1560-L1563

https://github.com/cosmology-finance/cosmology/blob/master/packages/protobufs/bin/gen-proto.js

# Backlog

- [x] #20 
- [x] #31
- [x] #16

- [ ] existing research/prototype https://github.com/pyramation/osmosis-protobufs and https://github.com/cosmology-finance/cosmology/tree/master/packages/protobufs

- [x] potentially use docker to containerize https://github.com/FedeBev/protobuf-node

- [x] how to manage proto files
   - [x] in the repo, manually bundled
   - [x] using `GOPATH`
   - [x] git submodules
