### ISSUE TITLE
TypeScript Library

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/telescope#2]
- [x] Core Telescope Module
  - [x] #9 
  - [x] #11
  - [x] #10
- [x] Osmosis Telescope Module
  - [x] Implement osmosis-related protobuf messages 
  - [x] #95
  - [x] #15
- [x] Registry System
  - [x] Loading channels and IBC Denominations for networks
  - [ ] Canonicalizing access symbols and denominations, and exponents
- [x] Agnostic Signing
  - [x] Will be designed to sign transactions with keplr or cosmjs
- [x] Interactive CLI
  - [x]  research https://github.com/oclif/oclif
