### ISSUE TITLE
cosmjs epic

### ISSUE THREAD

**Issue by pyramation** [osmosis-labs/telescope#237]
- [x] https://github.com/osmosis-labs/telescope/issues/66
- [x] https://github.com/osmosis-labs/telescope/issues/235
- [x] https://github.com/osmosis-labs/telescope/issues/236
