### ISSUE TITLE
Data Layer and Message Composer

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/telescope#3]
- [ ] Compose messages for signing
- [ ] Calculating swaps
- [ ] Pool routing
- [ ] Automate a series of messages
- [ ] Higher-level compositions, e.g. allow users to specify an investment strategy
