### ISSUE TITLE
Keplr and User Interface Integration

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/telescope#4]
- [ ] Keplr Integration
  - [ ] (will be built to allow signing via keplr, or cosmjs for lower-level utilities)
  - [ ] Visual developer debugging tool similar to:
  - [ ] https://metamask.github.io/test-dapp/
- [ ] UI Kit 
  - [ ] theming done super easily
  - [ ] storybook UI for documentation
  - [ ] basic components such as
  - [ ] connect wallet
  - [ ] swap tokens
  - [ ] join pool
  - [ ] lock tokens
  - [ ] etc.
- [ ] react tools
  - [ ] hooks like https://wagmi.sh/
