### ISSUE TITLE
Testing and Documentation

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/telescope#5]
### Todo
- [ ] - [ ] TDD development for all modules
- [ ] Fixtures for all necessary endpoints
- [ ] Docker image with local testing
- [ ] local version of osmosis, with pools, etc.	
- [ ] Boilerplate for testing
- [ ] API docs

### Example Dapps

- [ ] a webpage with LBP for a token launch 
- [ ] a webpage that allows users to lock tokens into a liquidity pool
- [ ] a webpage with token swap to allow users to buy token
