### ISSUE TITLE
final passes

### ISSUE THREAD

**Issue by pyramation** [osmosis-labs/telescope#54]
# todo
 
- [ ] #66
- [ ] #72  
- [x] #78
- [x] CLI - or example usage in practice 
- [ ] #79
- [ ] #80
# review

- [x]  Empty Files - annotations.ts (google)
- [x] "unsupported Service type. Contact Maintainers" inside parse.ts
- [x] #56 
- [x] #57
- [x] #58
- [x] #59
- [x] #60 
- [x] #61 
- [x] #62
- [x] #63 
- [x] #64 
- [x] #65
- [x] #67 
- [x] #68 
- [x] #71
- [x] #74 
- [x] #75 
- [x] top-level bundle (index.ts files)
