### ISSUE TITLE
Utilities

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/telescope#6]
- [ ] “auto-compounding” and staking automation with IBC routing
  - [ ] LP rewards to staking LP
  - [ ] LP rewards to staking coins
  - [ ] staking rewards to staking LP 
  - [ ] staking rewards to staking coins
- [ ] Authz Integration
  - [ ] Integrated with auto-compounding functionality
