### ISSUE TITLE
Example Apps

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/telescope#7]
- [ ] a webpage with LBP for a token launch 
- [ ] a webpage that allows users to lock tokens into a liquidity pool
- [ ] a webpage with token swap to allow users to buy token
