### ISSUE TITLE
App Boilerplate Generator

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/telescope#8]
This gives users “rails” they need for the correct JS architecture to build apps fast and correctly. 

- [ ] user can set up a modern web app, wired up with Telescope
  - [ ] api clients + local state
- [ ] ready to build out-of-the-box with pre-built components 
  - [ ] connect wallet
  - [ ] staking
  - [ ] themeable view components
- [ ] Registry
  - [ ] integration with cosmos-registry
  - [ ] registry for pluggable cosmos chain telescope modules, including:
    - [ ] wallets
    - [ ] queries
    - [ ] messages
    - [ ] IBC channels, denominations
- [ ] create-cosmos-app
  - [ ] CLI for generating boilerplates
- [ ] Integrations
  - [ ] create-react-app https://github.com/facebook/create-react-app/blob/main/packages/create-react-app/createReactApp.js
  - [ ] next.js
  - [ ] starport boilerplate
